# Reusable publish workflow for NPM packages
#   - dual publication (to GitHub packages and NPM)
#   - single package per repo (no mono-repo support)
name: Build and Publish

on:
  release:
    types: [published]

jobs:
  publish:
    name: Build and Publish

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Establish Package Version
        run: |
          release='${{ github.event.release.tag_name }}'
          version=`echo $release | cut -b2-`
          if ! echo $release | grep -q '^v[0-9]\+\.[0-9]\+\.[0-9]\+(-.+)$'; then
            echo "Release name must be in the format of 'vX.Y.Z[-anything]', got '$release'"
            exit 1
          fi
          sed -i -r "s/\"version\": *\".+\"/\"version\": \"$version\"/" package.json
      - name: Install Dependencies
        run: npm ci
      - name: Build Distributables
        run: |
          npm run clean # for paranoia
          npm run build
      - name: Publish to NPM
        run: |
          touch $HOME/.npmrc
          chmod 0600 $HOME/.npmrc
          cat << EOF > ~/.npmrc
          //registry.npmjs.org/:_authToken=${NPM_TOKEN}
          @xeger:registry=https://registry.npmjs.org/
          EOF
          npm publish --workspaces
        env:
          NPM_TOKEN: "${{ secrets.NPM_TOKEN }}"
      - name: Publish to GitHub
        run: |
          touch $HOME/.npmrc
          chmod 0600 $HOME/.npmrc
          cat << EOF > ~/.npmrc
          //npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}
          @xeger:registry=https://npm.pkg.github.com/
          EOF
          npm publish --workspaces
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
